### PR TITLE
Fix #293: The "Who's online" location is broken

### LINKED ISSUE #293: The "Who's online" location is broken

### PR DESCRIPTION
**Pull request by lairdshaw**
Resolves #293

Supersedes #266 (There's nothing especially wrong with that PR except for its minor failure to remove a mistaken define of NO_ONLINE; I just happened to implement my own fix in the course of all the other fixes I'm submitting tonight).

This PR honours the comment @euantorano made
[here](https://github.com/MyBBStuff/MyAlerts/pull/266#issuecomment-593251171) indicating that a location should be set for the modal. There is, then, never any reason to define NO_ONLINE for any functionality of this plugin.

### CODE REVIEW

**Comment by Eldenroot** [comment]
@euantorano - please, could you merge these PRs?

@lairdshaw - thank you so much for your time and PRs! I am waiting for the updated version, or your fork :)

**Comment by euantorano** [comment]
I’ll review as soon as I can. I’ve been very busy the last few weeks, but hoping I’ll get a chance to review this week. On 18 Jun 2023, at 21:12, Eldenroot ***@***.***> wrote:﻿
@euantorano - please, could you merge these PRs?
@lairdshaw - thank you so much for your time and PRs! I am waiting for the updated version, or your fork :)

**Comment by Eldenroot** [comment]
@euantorano - OK, sounds good! I am asking because more PRs with fixes are under the way and we are waiting for you to merge these 8 opened PRs...

File: inc/plugins/myalerts.php [hunk 1]
```diff
@@ -859,26 +859,36 @@ function myalerts_datahandler_user_insert(&$dataHandler)
...
 
+$plugins->add_hook(
+	'fetch_wol_activity_end',
+	'myalerts_online_activity'
+);
+function myalerts_online_activity($user_activity)
+{
+	if ($user_activity['activity'] == 'unknown') {
+		$split_loc = explode('.php', $user_activity['location']);
+		$filename = my_substr($split_loc[0], -my_strpos(strrev($split_loc[0]), '/'));
```
Comment (euantorano) [inline inc/plugins/myalerts.php:870]: This may be easier to do with `basename` if I'm understanding the logic correctly?

Comment (lairdshaw) [reply inc/plugins/myalerts.php:870]: Yep, I shamelessly ripped those lines from lines [#26](https://github.com/mybb/mybb/blob/a4dc072b3f4a9beed0d0686ffa6b6c0d1e343d59/inc/functions_online.php#L26) and [#33](https://github.com/mybb/mybb/blob/a4dc072b3f4a9beed0d0686ffa6b6c0d1e343d59/inc/functions_online.php#L33) of `inc/functions_online.php` after confirming that the logic was correct. We *could* simplify the code a little with your suggestions, although there'd be some admittedly only hypothetical failure cases for locations of, e.g., "alerts.php/test?abc=def", and "rootpluginscript.php/alerts". They're only hypothetical 'cos they don't seem like plausible returns of `get_current_location()` in `inc/functions.php`, so I guess it's a choice between purity (avoiding unrealisable failure cases) and simplicity...

Comment (euantorano) [reply inc/plugins/myalerts.php:870]: OK, I hadn't realised it as copied out of the core. In that case, we'll leave it as it is.
