### PR TITLE
Fix #304: Alert (auto)updating is broken

### LINKED ISSUE #304: Alert (auto)updating is broken
Problems:

1. The update Javascript is using the wrong variable: `data` instead of `data.template`.
2. Even if it were using the right variable, the update Javascript prepends the latest alerts to the list regardless of whether or not they are new, so, even if working, it would create duplicates.

As also noted here: https://github.com/MyBBStuff/MyAlerts/pull/284#issuecomment-1581378952

### PR DESCRIPTION
**Pull request by lairdshaw**
Resolves #304

### CODE REVIEW

File: jscripts/myalerts.js [hunk 1]
```diff
@@ -4,22 +4,35 @@
...
         var module = function MyAlerts() {
-            var unreadAlertsProxy = $.proxy(this.getUnreadAlerts, this),
+            var latestAlertsProxy = $.proxy(this.getLatestAlerts, this),
                 deleteAlertProxy = $.proxy(this.deleteAlert, this),
                 markAllReadProxy = $.proxy(this.markAllRead, this),
                 markReadAlertProxy = $.proxy(this.markReadAlert, this),
                 bodySelector = $("body");
 
-            bodySelector.on("click", "#getUnreadAlerts", unreadAlertsProxy);
+            var urlGetLatest = (typeof myAlertsBcMode !== 'undefined' && myAlertsBcMode == '1')
```
Comment (euantorano) [inline jscripts/myalerts.js:13]: Might just be me, but I can't see where this gets set in this merge request?

Comment (lairdshaw) [reply jscripts/myalerts.js:13]: You're right, it's not set in this merge request. It was set in #299 which I merged myself after flagging I'd do so after about a week in the absence of objections. You can still object to it though!

**Comment by euantorano** [comment]
Nah its all good, no objections here. Just wanted to make sure there wasn't something missing!
