### PR TITLE
Fix #206 Incorrect information on installed alert types due to out-of-sync cache

### LINKED ISSUE #206: Incorrect information on installed alert types due to out-of-sync cache
`MybbStuff_MyAlerts_AlertTypeManager` is not called in `myalerts_uninstall()` to synchronize the `mybbstuff_myalerts_alert_types` datacache for installed alert types, making the plugin skip alert types upon second installation.
Reproducible when adding or modifying core alert types.

### PR DESCRIPTION
**Pull request by Devilshakerz**
#206

### CODE REVIEW

File: inc/plugins/myalerts.php [hunk 1]
```diff
@@ -163,6 +163,8 @@ function myalerts_uninstall()
 	$PL->stylesheet_delete('alerts.css');
 
 	$db->delete_query('tasks', 'file = \'myalerts\'');
+
+    $cache->delete('mybbstuff_myalerts_alert_types');
```
Comment (euantorano) [inline inc/plugins/myalerts.php]: Indentation looks a little bit out here, but I can live with that.
